### ISSUE TITLE
【レッスンクリエイト画面】動画の説明入力欄をつくる

### ISSUE THREAD

**Issue by ogu1211** [Spologics/web#53]
アップした動画の説明欄を設ける。
（各レッスンページの動画の右側に表示されているイメージ）

**Comment by mtbamboon** [comment]
レッスン作成時に説明を追加しました。
各レッスンではとりあえず動画の下に表示させています。
自分が作成したレッスンであれば編集可能。

**Comment by ogu1211** [comment]
確認しました。あざます！
