### ISSUE TITLE
【セッティング】Profile、Password、Sports

### ISSUE THREAD

**Issue by chaboze** [Spologics/web#60]
・All
　－情報変更したら、「変更完了しました」の文章掲出
・Profile
　－チーム名入力欄作成
　－descriptionをProfile画面に移動
・Password
　－変更する際に、現在のパスワードを入力させるフォーム作成
　－パスワード変更の条件に入力された現在のパスワードが正しいかの条件追加
・Sports
　－冒頭に「現在取り組んでいるスポーツにチェックしてください」と一文追加
　　⇒できれば、コーチは「現在指導可能なスポーツにチェックしてください」という文章に出し分けたい（優先度低）

**Comment by mtbamboon** [comment]
上記すべて対応済み。
